// File: src-tauri/src/models/mod.rs
pub mod account;
pub mod analytics;
pub mod budget;
pub mod category;
pub mod credit_card;
pub mod currency;
pub mod installment;
pub mod recurring;
pub mod template;
pub mod transactions;
